version: "3.9"

services:
  app:
    build: .
    container_name: zig_app
    networks: [web]
    expose: [8080]        
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse
    volumes:
      - ./nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on: [app]
    networks: [web]
    restart: unless-stopped

networks:
  web:

volumes:
  certs:
  webroot: